name: CI

on:
  push:
    branches:
    - master
    tags:
  pull_request:

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:

          - name: Python 3.6 with minimal dependencies
            os: ubuntu-latest
            python: 3.6
            toxenv: py36-minimal

          - name: Python 3.6
            os: ubuntu-latest
            python: 3.6
            toxenv: py36

          - name: Python 3.7
            os: ubuntu-latest
            python: 3.7
            toxenv: py37

          - name: Python 3.7 with Astropy dev
            os: ubuntu-latest
            python: 3.7
            toxenv: py37-astropydev

          - name: Python 3.8 with code coverage
            os: ubuntu-latest
            python: 3.8
            toxenv: py38-cov

          - name: Python 3.8 with Numpy dev
            os: ubuntu-latest
            python: 3.8
            toxenv: py38-numpydev

          - name: Python 3.9
            os: ubuntu-latest
            python: 3.9
            toxenv: py39

          - name: Python 3.8 (Windows)
            os: windows-latest
            python: 3.8
            toxenv: py38
            toxposargs: --durations=50

          - name: Python 3.8 (MacOS X)
            os: macos-latest
            python: 3.8
            toxenv: py38

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install language-pack-fr and tzdata
      if: startsWith(matrix.os, 'ubuntu')
      run: sudo apt-get install language-pack-fr tzdata
    - name: Install Python dependencies
      run: python -m pip install --upgrade tox codecov
    - name: Run tests
      run: tox ${{ matrix.toxargs }} -e ${{ matrix.toxenv }} -- ${{ matrix.toxposargs }}
    - name: Upload coverage to codecov
      if: ${{ contains(matrix.toxenv,'-cov') }}
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
